version: '2.1'

services:
  xtreme-photographics:
    image: xtreme-photographics
    build: .
    environment:
      NODE_ENV: development
    ports:
      - :
      - 9229:9229
    ## set your startup file here
    command: node --inspect index.js